# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "kibana"
  config.vm.box = "kapke/xenial64-lxc"

  config.vm.provider :lxc do |lxc, override|
    lxc.container_name = "kibana"
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'test.yml'
    # ansible.galaxy_role_file='galaxy.yml'
  end
end
